version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mymovie-virginia"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1t7v8p5bz5v29"
s3_prefix = "mymovie-virginia"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnviromentType=\"stg\""
image_repositories = []
profile = "dev"
confirm_changeset = true
